browser=Chrome
headless=false
testurl=https://tch.psinfi.com/
username=prakash.d@primesoftinc.com
password=Test@12345
executedby=Bhavani

#Account Reporting Request
TCHPaymentSevice=TCH
TCHReportType=ABAR,AADR,AATR
RoutingNumber=021040078

#Retrieval Request Report
TCHMessageType=Value
TCHMessage=Pacs.008
GeratedReportNoData=NO DATA



#Broadcast Messages
TCHBMType=PING
GeratedReportNoData=NO DATA

#Batchs 
BatchPaymentService=TCH
TCH=TCH_001

#Batchs Individual Run
BTServiceNameFN=TCH
TCHBatchName=TCH_001


BatchRunsuccmsg=Batch executed successfully



#Dynamic Reports --> no - currenttime+index.html --> yes - index.html
overridereports=yes

#Screenshots to be attached in extent reports#
passedstepsscreenshot=yes
failedstepsscreenshot=yes
skippedstepsscreenshot=yes
infostepsscreenshot=yes


