browser=Chrome
headless=false
testurl=https://production.psinfi.com/
ion.psinfi.com/
username=prakash.d@primesoftinc.com
password=Test@12345
executedby=Bhavani

#Account Reporting Request
FednowPaymentSevice=Fednow
FedNowReportType=ABAR,AADR,AATR
RoutingNumber=011054444
FedwirePaymentSevice=Fedwire
FedwireReportType=ABAR,ETOT,DTLR,DTLS
RoutingNumber=011054444

#Fedwire DTLR and DTLS Flow
seqFromNum=000001
seqToNum=000010

#Retrieval Request Report
FednowMessageType=Value
FednowMessage=Pacs.008
GeneratedReportNoData=NO DATA

FedwireMessageType=Value
FedwireMessage=Pacs.008
FedwireFlowType=Sent


#Broadcast Messages
FednowBMType=PING
FedwireBMPBType=PING
FedwireBMFWBType=OPEN,CLSD
GeratedReportNoData=NO DATA

#Batchs 
BatchPaymentService=Fednow,Fedwire
Fednow=TestBatch_Automation,FDN_Certified_TC_OB
Fedwire=New,Fedwire_Certified_TC_OB

#Batchs Individual Run
BTServiceNameFN=Fednow
BTServiceNameFW=Fedwire
FednowBatchName=CitiBank_FDN_Prod_Automation
FedwireBatchName=CitiBank_FDW_Prod_Automation

#FednowBatchName=FDN_Certified_TC_OB
#FedwireBatchName=NEW

BatchRunsuccmsg=Batch executed successfully



#Dynamic Reports --> no - currenttime+index.html --> yes - index.html
overridereports=yes

#Screenshots to be attached in extent reports#
passedstepsscreenshot=yes
failedstepsscreenshot=yes
skippedstepsscreenshot=yes
infostepsscreenshot=yes


